### ISSUE TITLE
npm run dev的时候报错, 各位知道怎么回事儿吗

### ISSUE THREAD

**Issue by hyuanyuanlisiwei** [Meituan-Dianping/mpvue#1058]
VM116:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'call' of undefined 
 TypeError: Cannot read property 'call' of undefined
    at t (http://127.0.0.1:55883/appservice/common/manifest.js:16:90)
    at Object.NHnr (http://127.0.0.1:55883/appservice/app.js:16:67)
    at t (http://127.0.0.1:55883/appservice/common/manifest.js:16:91)
    at Object.global.webpackJsonp (http://127.0.0.1:55883/appservice/common/manifest.js:12:11)
    at http://127.0.0.1:55883/appservice/app.js:5:8
    at require (http://127.0.0.1:55883/appservice/__dev__/WAService.js:23:13516)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:55883/appservice/appservice?t=1538050933549:6948:23)
console.error @ VM116:1
(anonymous) @ WAService.js:15
(anonymous) @ WAService.js:6
e @ appservice?t=1538050933549:6685
window.onerror @ VM116:1
scriptLoaded @ appservice?t=1538050933549:6948
WAService.js:19

**Comment by Stevenzwzhai** [comment]
这个问题解决了？
