### ISSUE TITLE
引入vue-amap

### ISSUE THREAD

**Issue by yuanfangice** [Meituan-Dianping/mpvue#1161]
## 引入高德地图报错

**引入代码：**

main.js
import VueAMap from 'vue-amap';
Vue.use(VueAMap);
VueAMap.initAMapApiLoader({
    key: 'b8f04aa5ba51b2d24b92fe4e8903e40f',
    plugin: ['AMap.Autocomplete', 'AMap.PlaceSearch', 'AMap.Scale', 'AMap.OverView', 'AMap.ToolBar', 'AMap.MapType', 'AMap.PolyEditor', 'AMap.CircleEditor'],
    // 默认高德 sdk 版本为 1.4.4
    v: '1.4.4'
});

报错：
VM186:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'AMap' of undefined 
 TypeError: Cannot read property 'AMap' of undefined
    at t.load (http://127.0.0.1:51107/appservice/common/vendor.js:6865:40)
    at Object.s [as initAMapApiLoader] (http://127.0.0.1:51107/appservice/common/vendor.js:5667:67)
    at Object.<anonymous> (http://127.0.0.1:51107/appservice/app.js:22:52)
    at __webpack_require__ (http://127.0.0.1:51107/appservice/common/manifest.js:71:31)
    at Object.webpackJsonpCallback [as webpackJsonp] (http://127.0.0.1:51107/appservice/common/manifest.js:38:26)
    at http://127.0.0.1:51107/appservice/app.js:5:8
    at require (http://127.0.0.1:51107/appservice/__dev__/WAService.js:18:26712)
    at http://127.0.0.1:51107/appservice/appservice:1302:9

**Comment by strange-fish** [comment]
这又不是真正的vue，只是一套语法糖而已。组件不能随便用的。

**Comment by yuanfangice** [comment]
> 这又不是真正的vue，只是一套语法糖而已。组件不能随便用的。

那有没有类似的mpvue-amap呢

**Comment by strange-fish** [comment]
> > 这又不是真正的vue，只是一套语法糖而已。组件不能随便用的。
> 
> 那有没有类似的mpvue-amap呢

直接使用wx.openLocation不可以满足你的要求吗？

**Comment by zxzhgk** [comment]
可以使用微信小程序的地图插件

**Comment by hucq** [comment]
> 这又不是真正的vue，只是一套语法糖而已。组件不能随便用的。

1. 这是真正的 vue。从设计上看 vue 并不局限运行环境是浏览器还是小程序，或者weex。
2. 但显然，在浏览器平台上实现的组件，并不一定能运行在小程序上，这取决于是否有使用平台差异的api。
3. 譬如，如果组件中使用了 dom, bom，那小程序没有同等的实现，会报错
4. 如果这个组件提供了小程序版本的实现，可以直接使用，mpvue 能直接使用 小程序的自定义组件
