### ISSUE TITLE
项目执行 npm run build 时偶尔出现错误，重新执行一遍一般就好了

### ISSUE THREAD

**Issue by zxzhgk** [Meituan-Dianping/mpvue#1222]
## [问题简单描述]
项目执行 npm run build  时 偶尔出现此错误

**问题复现步骤：**

执行 npm run build 

**期望的表现：**

编译能正常执行，现在偶尔会出现错误，重新执行就正常了

**观察到的表现：**

0 info it worked if it ends with ok
1 verbose cli [ 'D:\\node\\node.exe',
1 verbose cli   'D:\\node\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@5.5.1
3 info using node@v8.9.2
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle hdxcx@1.0.0~prebuild: hdxcx@1.0.0
6 info lifecycle hdxcx@1.0.0~build: hdxcx@1.0.0
7 verbose lifecycle hdxcx@1.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle hdxcx@1.0.0~build: PATH: D:\node\node_modules\npm\bin\node-gyp-bin;F:\code\hdxcx\node_modules\.bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\Git\cmd;D:\node\;C:\Program Files\TortoiseSVN\bin;C:\WINDOWS\System32\OpenSSH\;D:\vscode\Microsoft VS Code\bin;C:\Users\xuxu\AppData\Local\Microsoft\WindowsApps;C:\Users\xuxu\AppData\Roaming\npm;D:\vscode\Microsoft VS Code\bin;D:\Fiddler;%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;
9 verbose lifecycle hdxcx@1.0.0~build: CWD: F:\code\hdxcx
10 silly lifecycle hdxcx@1.0.0~build: Args: [ '/d /s /c', 'node build/build.js' ]
11 silly lifecycle hdxcx@1.0.0~build: Returned: code: 1  signal: null
12 info lifecycle hdxcx@1.0.0~build: Failed to exec build script
13 verbose stack Error: hdxcx@1.0.0 build: `node build/build.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (D:\node\node_modules\npm\node_modules\npm-lifecycle\index.js:280:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (D:\node\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid hdxcx@1.0.0
15 verbose cwd F:\code\hdxcx
16 verbose Windows_NT 10.0.17134
17 verbose argv "D:\\node\\node.exe" "D:\\node\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v8.9.2
19 verbose npm  v5.5.1
20 error code ELIFECYCLE
21 error errno 1
22 error hdxcx@1.0.0 build: `node build/build.js`
22 error Exit status 1
23 error Failed at the hdxcx@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by zxzhgk** [comment]
已解决 此问题是编译后dist目录不为空时，会导致。可在编译前手动清空dist 目录
