### ISSUE TITLE
在mpvue项目输入npm run dev后，在微信开发者工具的控制台报如下错误

### ISSUE THREAD

**Issue by hellojackhui** [Meituan-Dianping/mpvue#1228]
## [问题简单描述]

```sh
thirdScriptError 
 sdk uncaught third Error 
 global.webpackJsonp is not a function 
 TypeError: global.webpackJsonp is not a function
    at http://127.0.0.1:34667/appservice/app.js:3:8
    at require (http://127.0.0.1:34667/appservice/__dev__/WAService.js:1:718745)
    at <anonymous>:1:1
    at HTMLScriptElement.scriptLoaded (http://127.0.0.1:34667/appservice/appservice?t=1543480357598:1422:23)
```

报错导致每个页面的js功能失效，html和css可以显示

网上找了半天，什么在HTMLWebpackPlugin添加chunks，没有作用，所以希望大佬能帮忙提些建议，解决一下！

**Comment by F-loat** [comment]
更新下 webpack-mpvue-asset-plugin 试试

**Comment by hellojackhui** [comment]
多谢大佬，已解决，的确是 webpack-mpvue-asset-plugin版本问题
