### ISSUE TITLE
使用最新版本报UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'source' of undefined

### ISSUE THREAD

**Issue by teri5354** [Meituan-Dianping/mpvue#1339]
"mpvue": "^1.1.0",
 "mpvue-loader": "1.2.0",

运行npm run dev之后，报UnhandledPromiseRejectionWarning
一开始以为是issues一样的解决方法，npm install --save-dev prettier@~1.12.0===》npm run dev还是不行，仍然报UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'source' of undefined错误，不知道哪里没有配置好

 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'source' of undefined
    at Compiler.compiler.plugin (/Users/XXX/node_modules/webpack-mpvue-vendor-plugin/index.js:17:29)
    at next (/Users/XXX/node_modules/webpack/node_modules/tapable/lib/Tapable.js:204:14)
    at LastCallWebpackPlugin.process (/Users/XXX/node_modules/last-call-webpack-plugin/index.js:126:12)

**Comment by hucq** [comment]
暂时看不出来问题，你可以尝试检查一下 webpack 版本是否 2.x

**Comment by teri5354** [comment]
"webpack": "^3.11.0",
    "webpack-dev-middleware-hard-disk": "^1.12.0",
    "webpack-merge": "^4.1.0",

是3.11的，有问题吗？

**Comment by teri5354** [comment]
按官方的文档是没办法顺利把老版本升级过来的，目前的坑正在一个个的填，非常郁闷，下个项目应该不会再选这个框架了
