### ISSUE TITLE
mac下新建一个mpvue项目未做任何改动npm run dev报错

### ISSUE THREAD

**Issue by maxcheers86** [Meituan-Dianping/mpvue#1363]
以前的项目还是可以跑的，
 "scripts": {
    "dev": "node build/dev-server.js",
    "start": "node build/dev-server.js",
    "build": "node build/build.js"
  },
现在的版本多了好些东西
 "scripts": {
    "dev:wx": "node build/dev-server.js wx",
    "start:wx": "npm run dev:wx",
    "build:wx": "node build/build.js wx",
    "dev:swan": "node build/dev-server.js swan",
    "start:swan": "npm run dev:swan",
    "build:swan": "node build/build.js swan",
    "dev": "node build/dev-server.js wx",
    "start": "npm run dev",
    "build": "node build/build.js wx",
    "lint": "eslint --ext .js,.vue src"
  },

报错信息：
 error  in ./src/pages/counter/index.vue

Module build failed: Error: Final loader didn't return a Buffer or String
    at runLoaders (/Users/middlebaby/x/pkchat/node_modules/webpack/lib/NormalModule.js:204:46)

**Comment by VecHK** [comment]
我按照官网上的 [快速上手](http://mpvue.com/mpvue/quickstart/#1-mpvue)  也遇到同样的问题。

**Comment by zybieku** [comment]
window上也有这个问题

**Comment by joze2016** [comment]
应该是新版本引进的一个问题，下面方法能够暂时解决。等下个新版本吧。
修改package.json
"mpvue": "1.0.18"
"mpvue-template-compiler": "1.0.18"

**Comment by zybieku** [comment]
"mpvue": "^1.0.18",
 "mpvue-loader": "1.1.4",
"mpvue-template-compiler": "^1.0.18",
 "mpvue-webpack-target": "^1.0.3",
看到群里有伙计 现在测试出来的版本也可行，给你们参考

**Comment by SnowMusic** [comment]
在`npm install `之前修改package.json为
"mpvue": "1.0.18"
"mpvue-template-compiler": "1.0.18"
可暂时性解决

**Comment by tanghw** [comment]
> 应该是新版本引进的一个问题，下面方法能够暂时解决。等下个新版本吧。
> 修改package.json
> "mpvue": "1.0.18"
> "mpvue-template-compiler": "1.0.18"

此方法ok

**Comment by Dewyzee** [comment]
目前需要手动更新下版本号，mpvue以及mpvue-template-compiler才发布的了新的版本，模板还没有更新

**Comment by littlePig-zzf** [comment]
什么时候才更新模板

**Comment by Dewyzee** [comment]
@littlePig-zzf 当前新创建的模板应该不存在该问题，npm默认会安装最新的版本。如果mpvue-loader版本被锁，确认下是否为1.2.0版本及以上

**Comment by charmtiger** [comment]
我将 mpvue mpvue-template-compiler 版本都设置为 1.0.18(缓存已清空)，但是仍然报这个错，希望可以给个其他包本版号

**Comment by littlePig-zzf** [comment]
> 我将 mpvue mpvue-template-compiler 版本都设置为 1.0.18(缓存已清空)，但是仍然报这个错，希望可以给个其他包本版号

我的是1.0.13，然后mpvue-loader是1.1.4

**Comment by SnowMusic** [comment]
> > 我将 mpvue mpvue-template-compiler 版本都设置为 1.0.18(缓存已清空)，但是仍然报这个错，希望可以给个其他包本版号
> 
> mpvue-loader 升级到 1.2.2，具体操作可以参考：[mpvue-loader 1.2.2](https://github.com/mpvue/mpvue-loader/releases/tag/1.2.2)

请问作为member您解决了吗或者给出具体操作方式了吗就close掉，这么多人反馈这个问题，我直接lock住mpvue-loader并没有解决这个问题，反而之前直接锁住mpvue和tempile的方式也不行了

**Comment by beijingqingnian** [comment]
/wx/my-project/node_modules/last-call-webpack-plugin/src/index.js:170
    compiler.hooks.compilation.tap(
                   ^

TypeError: Cannot read property 'compilation' of undefined
    at OptimizeCssAssetsWebpackPlugin.apply (/wx/my-project/node_modules/last-call-webpack-plugin/src/index.js:170:20)
    at Compiler.apply (/wx/my-project/node_modules/webpack/node_modules/tapable/lib/Tapable.js:375:16)
    at webpack (/wx/my-project/node_modules/webpack/lib/webpack.js:33:19)
    at Object.<anonymous> (/wx/my-project/build/dev-server.js:27:16)
    at Module._compile (internal/modules/cjs/loader.js:759:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:770:10)
    at Module.load (internal/modules/cjs/loader.js:628:32)
    at Function.Module._load (internal/modules/cjs/loader.js:555:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:822:10)
    at internal/main/run_main_module.js:17:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@1.0.0 dev: `node build/dev-server.js wx`
npm ERR! Exit status 1

**Comment by near2sea** [comment]
> 在`npm install `之前修改package.json为
> "mpvue": "1.0.18"
> "mpvue-template-compiler": "1.0.18"
> 可暂时性解决

此方法可行
