### ISSUE TITLE
项目依赖升级后报错   Cannot read property 'template' of undefined

### ISSUE THREAD

**Issue by b779542115** [Meituan-Dianping/mpvue#1371]
### 将mpvue相关依赖升级后报错，版本号如下:
 "mpvue": "^1.0.20",
 "mpvue-template-compiler": "^1.0.20",
 "mpvue-loader": "^1.2.0"

## 编译报错信息

G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\mpvue-loader\lib\mp-compiler\util.js:19
  const filePath = `/${resolveSrc(context, file)}.${fileExt.template}`
                                                            ^

TypeError: Cannot read property 'template' of undefined
    at getCompInfo (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\mpvue-loader\lib\mp-compiler\util.js:19:61)
    at createPageMPML (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\mpvue-loader\lib\mp-compiler\index.js:41:30)
    at resolve (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\mpvue-loader\lib\mp-compiler\index.js:196:9)
    at onResolve (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\Resolver.js:70:11)
    at innerCallback (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\Resolver.js:143:22)
    at callbackWrapper (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at next (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\tapable\lib\Tapable.js:249:35)
    at G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:39:22
    at callbackWrapper (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at innerCallback (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\Resolver.js:143:22)
    at callbackWrapper (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at next (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\tapable\lib\Tapable.js:249:35)
    at innerCallback (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\Resolver.js:143:22)
    at callbackWrapper (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\createInnerCallback.js:10:21)
    at next (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\tapable\lib\Tapable.js:249:35)
    at resolver.doResolve.createInnerCallback (G:\NewUUFE\MiniProgram\Stunner\admin-package\node_modules\enhanced-resolve\lib\DescriptionFilePlugin.js:41:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! uxu@1.3.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the uxu@1.3.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\77954\AppData\Roaming\npm-cache\_logs\2019-02-12T07_06_53_075Z-debug.log

**Comment by liufeics** [comment]
尝试锁定loader版本 然后 用yarn编译

**Comment by b779542115** [comment]
@liufeics   还是不行  暂时先回退版本了

**Comment by NinjaJin** [comment]
我这边
"mpvue": "^1.0.11",
"mpvue-template-compiler": "^1.0.11",
"mpvue-loader": "^1.1.2"
也报同样错误。。

**Comment by b779542115** [comment]
@NinjaJin  https://github.com/Meituan-Dianping/mpvue/issues/1363#issuecomment-458790141 可以先试试这个

**Comment by F-loat** [comment]
可以参考 https://github.com/F-loat/mpvue-quickstart/commit/eb4ac7ec8ba7d4dc4742e3f9e382b1762144cd53 修改构建配置

**Comment by F-loat** [comment]
可以参考 https://github.com/F-loat/mpvue-quickstart/commit/eb4ac7ec8ba7d4dc4742e3f9e382b1762144cd53 修改构建配置

**Comment by b779542115** [comment]
> 可以参考 [F-loat/mpvue-quickstart@eb4ac7e](https://github.com/F-loat/mpvue-quickstart/commit/eb4ac7ec8ba7d4dc4742e3f9e382b1762144cd53) 修改构建配置

可以了 谢谢

**Comment by hucq** [comment]
### 修复方式：
升级 mpvue-loader 到 1.2.2，详情参见：https://github.com/mpvue/mpvue-loader/releases/tag/1.2.2
