### ISSUE TITLE
fileExt.platform 重新拉npm i 会出现platform报错问题

### ISSUE THREAD

**Issue by qzmly100** [Meituan-Dianping/mpvue#1630]
/Users/junfengye/jobs/wechat/pms-miniprog/node_modules/mpvue-template-compiler/build.js:5791
    console.log(fileExt.platform)
                        ^

TypeError: Cannot read property 'platform' of undefined
    at Object.compileToWxml (/Users/junfengye/jobs/wechat/pms-miniprog/node_modules/mpvue-template-compiler/build.js:5791:25)
    at genComponentWxml (/Users/junfengye/jobs/wechat/pms-miniprog/node_modules/mpvue-loader/lib/mp-compiler/index.js:45:75)
    at Timeout.createWxml [as _onTimeout] (/Users/junfengye/jobs/wechat/pms-miniprog/node_modules/mpvue-loader/lib/mp-compiler/index.js:92:19)
    at ontimeout (timers.js:511:34)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)

**Comment by qzmly100** [comment]
之前好好的，是不是又升级了？我下一步怎么做？

**Comment by qzmly100** [comment]
https://github.com/Meituan-Dianping/mpvue/issues/1420
