### ISSUE TITLE
头条小程序npm run dev:tt 直接报错

### ISSUE THREAD

**Issue by myhuangqiang** [Meituan-Dianping/mpvue#1639]
## [扼要问题描述]
npm run dev:tt 将dist文件下的tt文件夹导入头条小程序开发者工具包以下错误：

Unable to determine project type, microApp needs app.json，microGame needs game.json.
at BuildDist (C:Users iuxAppDataLocalProgramsytedanceide esourcesapp.asar.unpacked ode_modulesyted-tma-packdestindex.js:1:59867)
at C:Users iuxAppDataLocalProgramsytedanceide esourcesapp.asar.unpacked ode_modulesyted-tma-packdestindex.js:1:62305
at o (C:Users iuxAppDataLocalProgramsytedanceide esourcesapp.asar.unpackedsimulator-sdk 

**mpvue 版本号：**
"mpvue": "^2.0.0",
"mpvue-loader": "^2.0.0",
"mpvue-template-compiler": "^2.0.0",
"mpvue-webpack-target": "^1.0.3",
[mpvue@x.x.x]

**最小化复现代码：**

[建议提供最小化可运行的代码：附件或文本代码]

```
// 示例代码：
```

**问题复现步骤：**

1. npm run dev:tt
2. 导入开发者工具
3. 报错

**观察到的表现：**
![image](https://user-images.githubusercontent.com/25660665/59601604-1995fe80-9137-11e9-926e-7fbfe76abe8f.png)

[在这里描述观察到的表现]

**截图或动态图：**
![image](https://user-images.githubusercontent.com/25660665/59601625-23b7fd00-9137-11e9-8c52-492a3d3202de.png)

![复现步骤截图或gif图片](图片的 url)

**Comment by gao-mountain** [comment]
遇到一样的报错

**Comment by cxh1991** [comment]
最新mpvue/mpvue-quickstart生成的吗  还是老项目升级的？

**Comment by caolonggang** [comment]
新建项目，遇到同样的报错

**Comment by fangqingqing2** [comment]
> ## [扼要问题描述]
> npm run dev:tt 将dist文件下的tt文件夹导入头条小程序开发者工具包以下错误：
> 
> Unable to determine project type, microApp needs app.json，microGame needs game.json.
> at BuildDist (C:Users iuxAppDataLocalPrograms�ytedanceide esourcesapp.asar.unpacked ode_modules�yted-tma-packdestindex.js:1:59867)
> at C:Users iuxAppDataLocalPrograms�ytedanceide esourcesapp.asar.unpacked ode_modules�yted-tma-packdestindex.js:1:62305
> at o (C:Users iuxAppDataLocalPrograms�ytedanceide esourcesapp.asar.unpackedsimulator-sdk
> 
> **mpvue 版本号：**
> "mpvue": "^2.0.0",
> "mpvue-loader": "^2.0.0",
> "mpvue-template-compiler": "^2.0.0",
> "mpvue-webpack-target": "^1.0.3",
> [[mpvue@x.x.x](mailto:mpvue@x.x.x)]
> 
> **最小化复现代码：**
> 
> [建议提供最小化可运行的代码：附件或文本代码]
> 
> ```
> // 示例代码：
> ```
> 
> **问题复现步骤：**
> 
> 1. npm run dev:tt
> 2. 导入开发者工具
> 3. 报错
> 
> **观察到的表现：**
> ![image](https://user-images.githubusercontent.com/25660665/59601604-1995fe80-9137-11e9-926e-7fbfe76abe8f.png)
> 
> [在这里描述观察到的表现]
> 
> **截图或动态图：**
> ![image](https://user-images.githubusercontent.com/25660665/59601625-23b7fd00-9137-11e9-8c52-492a3d3202de.png)
> 




> ## [扼要问题描述]
> npm run dev:tt 将dist文件下的tt文件夹导入头条小程序开发者工具包以下错误：
> 
> Unable to determine project type, microApp needs app.json，microGame needs game.json.
> at BuildDist (C:Users iuxAppDataLocalPrograms�ytedanceide esourcesapp.asar.unpacked ode_modules�yted-tma-packdestindex.js:1:59867)
> at C:Users iuxAppDataLocalPrograms�ytedanceide esourcesapp.asar.unpacked ode_modules�yted-tma-packdestindex.js:1:62305
> at o (C:Users iuxAppDataLocalPrograms�ytedanceide esourcesapp.asar.unpackedsimulator-sdk
> 
> **mpvue 版本号：**
> "mpvue": "^2.0.0",
> "mpvue-loader": "^2.0.0",
> "mpvue-template-compiler": "^2.0.0",
> "mpvue-webpack-target": "^1.0.3",
> [[mpvue@x.x.x](mailto:mpvue@x.x.x)]
> 
> **最小化复现代码：**
> 
> [建议提供最小化可运行的代码：附件或文本代码]
> 
> ```
> // 示例代码：
> ```
> 
> **问题复现步骤：**
> 
> 1. npm run dev:tt
> 2. 导入开发者工具
> 3. 报错
> 
> **观察到的表现：**
> ![image](https://user-images.githubusercontent.com/25660665/59601604-1995fe80-9137-11e9-926e-7fbfe76abe8f.png)
> 
> [在这里描述观察到的表现]
> 
> **截图或动态图：**
> ![image](https://user-images.githubusercontent.com/25660665/59601625-23b7fd00-9137-11e9-8c52-492a3d3202de.png)
> 
> ![复现步骤截图或gif图片](图片的 url)

这个问题解决了吗？我现在也遇到了同样的问题

**Comment by fangqingqing2** [comment]
问题解决了吗？遇到了同样的问题

**Comment by fangqingqing2** [comment]
问题解决了吗？遇到了同样的问题

**Comment by fangqingqing2** [comment]
问题解决了吗？遇到了同样的问题，在线等啊

**Comment by haydenull** [comment]
试一下将dist/tt/project.config.json 的  miniprogramRoot 删除或者将值改为  "./"

![image](https://user-images.githubusercontent.com/17695989/63257063-8c446700-c2ab-11e9-82c4-04046f63c310.png)
