### ISSUE TITLE
重新npm i 就遇到报错了 提示有vue 莫非前几天我用了强制更新vue版本的原因？

### ISSUE THREAD

**Issue by qzmly100** [Meituan-Dianping/mpvue#1681]
error  in ./node_modules/mpvue-entry/dist/PagesMineCommentHouseDetailsAdd.js

Module build failed: Error: 

Vue packages version mismatch:

- vue@1.0.12
- mpvue-template-compiler@1.0.11

This may cause things to work incorrectly. Make sure to use the same version for both.
If you are using mpvue-loader, re-installing them should bump mpvue-template-compiler to the latest.

    at Object.<anonymous> (/Users/junfengye/jobs/wechat/pms-miniprog/node_modules/mpvue-template-compiler/index.js:8:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/junfengye/jobs/wechat/pms-miniprog/node_modules/mpvue-loader/lib/parser.js:1:78)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)

 error  in ./node_modules/mpvue-entry/dist/PagesMineCommentMessage.js

Module build failed: Error:

**Comment by qzmly100** [comment]
解决了 
锁定 mpvue-template-compiler@1.0.12 就可以了
