### ISSUE TITLE
没有内置对sass支持么

### ISSUE THREAD

**Issue by ranwawa** [Meituan-Dianping/mpvue#232]
# [问题简单描述]
在`style`标签打上`lang=scss`就提示没有安装依赖
没有用过webpack的人是不是必须先去学习webpack呢
**问题复现步骤:**

1. 根据官网步骤初始化项目
2. 在`src`中添加一个新的页面
3. 在`style`上添加了`lang`属性
4. npm run dev

**期望的表现:**
能够直接编译sass到css

**观察到的表现:**
```
 ERROR  Failed to compile with 1 errors09:46:56

This dependency was not found:

* !!../../../../node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../../../node_modules/mpvue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-6610613e","scoped":false,"hasInlineConfig":false}!px2rpx-loader?{"baseDpr":1,"rpxUnit":0.5}!postcss-loader?{"sourceMap":true}!less-loader?{"sourceMap":false}!../../../../node_modules/mpvue-loader/lib/selector?type=styles&index=0!./index.vue in ./src/pages/personal/home/index.vue

To install it, you can run: npm install --save !!../../../../node_modules/extract-text-webpack-plugin/loader.js?{"omit":1,"remove":true}!vue-style-loader!css-loader?{"minimize":false,"sourceMap":false}!../../../../node_modules/mpvue-loader/lib/style-compiler/index?{"vue":true,"id":"data-v-6610613e","scoped":false,"hasInlineConfig":false}!px2rpx-loader?{"baseDpr":1,"rpxUnit":0.5}!postcss-loader?{"sourceMap":true}!less-loader?{"sourceMap":false}!../../../../node_modules/mpvue-loader/lib/selector?type=styles&index=0!./index.vue
 WAIT  Compiling...09:47:17

```

**Comment by chackson** [comment]
自行安装后会出现以下的提示
 error  in ./src/components/selectSlider.vue

Module build failed: TypeError: Cannot read property 'for' of undefined
    at fixDefaultIterator (D:\work\cap-plugin-team\cap.plugin.community\cap.plugin.community.web\cap.plugin.community.web.frontend\src\main\webapp\dev\node_modules\mpvue-template-compiler\build.js:4104:22)
    at mark (D:\work\cap-plugin-team\cap.plugin.community\cap.plugin.community.web\cap.plugin.community.web.frontend\src\main\webapp\dev\node_modules\mpvue-template-compiler\build.js:4133:3)
    at markComponent (D:\work\cap-plugin-team\cap.plugin.community\cap.plugin.community.web\cap.plugin.community.web.frontend\src\main\webapp\dev\node_modules\mpvue-template-compiler\build.js:4195:3)
    at baseCompile (D:\work\cap-plugin-team\cap.plugin.community\cap.plugin.community.web\cap.plugin.community.web.frontend\src\main\webapp\dev\node_modules\mpvue-template-compiler\build.js:4211:13)
    at compile (D:\work\cap-plugin-team\cap.plugin.community\cap.plugin.community.web\cap.plugin.community.web.frontend\src\main\webapp\dev\node_modules\mpvue-template-compiler\build.js:3916:22)
    at Object.module.exports (D:\work\cap-plugin-team\cap.plugin.community\cap.plugin.community.web\cap.plugin.community.web.frontend\src\main\webapp\dev\node_modules\mpvue-loader\lib\template-compiler\index.js:37:18)

**Comment by lizesheng0313** [comment]
安装完了不管用啊 还是报错，引用的时候

**Comment by lizesheng0313** [comment]
请看报错  https://segmentfault.com/q/1010000016815846?_ea=4882953

**Comment by s1234567xb** [comment]
安装之后还是报错，是不是那个环节出错啦

**Comment by eillittwang** [comment]
安装报错的，可以试一下，其他版本的。
npm install -D node-sass@4.7.2 sass-loader@7.0.3
我安装这个版本的，是可以的
