### ISSUE TITLE
在mpvue里编写小程序自己的自定义组件的正确方式是什么？

### ISSUE THREAD

**Issue by rchunping** [Meituan-Dianping/mpvue#290]
因为一些性能优化需要 #181 ，我们把之前写的某些mpvue组件（尤其是那些在v-for中大量使用的组件）转成了小程序自己的 [Component](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/)

目前这些"原生“组件是放在 /src/native 下面，每个组件由4个文件组成
```bash
/src/native/child.js
/src/native/child.json
/src/native/child.wxss
/src/native/child.wxml
```
因为这些组件也是需要用到项目中其他js库，所以在<code>webpack.base.conf.js</code>里把 <code>native/child.js</code> 加到 entry里作为一个page来构建
其它<code>child.[json|json|wxss|wxml]</code>则是通过<code>CopyWebpackPlugin</code>复制到dist对应的目录中去

这种方式在之前一直使用正常。
今天因为 #289  这个问题更新了一下build配置，因为使用了新的webpack-mpvue-asset-plugin，
导致处理这些entry的时候会输出大量错误
```javascript
TypeError: Cannot read property 'source' of undefined
    at childChunks.forEach.item (D:\MpvueProjects\myproj\node_modules\webpack-mpvue-asset-plugin\index.js:26:53)
    at Array.forEach (<anonymous>)
    at compilation.chunks.forEach.commonChunk (D:\MpvueProjects\myproj\node_modules\webpack-mpvue-asset-plugin\index.js:20:21)
    at Array.forEach (<anonymous>)
    at Compiler.<anonymous> (D:\MpvueProjects\myproj\node_modules\webpack-mpvue-asset-plugin\index.js:15:24)
    at Compiler.applyPluginsAsyncSeries (D:\MpvueProjects\myproj\node_modules\tapable\lib\Tapable.js:206:13)
    at Compiler.emitAssets (D:\MpvueProjects\myproj\node_modules\webpack\lib\Compiler.js:308:7)
    at onCompiled (D:\MpvueProjects\myproj\node_modules\webpack\lib\Compiler.js:52:18)
    at D:\MpvueProjects\myproj\node_modules\webpack\lib\Compiler.js:499:13
    at next (D:\MpvueProjects\myproj\node_modules\tapable\lib\Tapable.js:202:11)
    at Compiler.<anonymous> (D:\MpvueProjects\myproj\node_modules\webpack\lib\CachePlugin.js:62:5)
    at Compiler.applyPluginsAsyncSeries (D:\MpvueProjects\myproj\node_modules\tapable\lib\Tapable.js:206:13)
    at D:\MpvueProjects\myproj\node_modules\webpack\lib\Compiler.js:496:10
    at Compilation.applyPluginsAsyncSeries (D:\MpvueProjects\myproj\node_modules\tapable\lib\Tapable.js:195:46)
    at self.applyPluginsAsync.err (D:\MpvueProjects\myproj\node_modules\webpack\lib\Compilation.js:649:19)
    at Compilation.applyPluginsAsyncSeries (D:\MpvueProjects\myproj\node_modules\tapable\lib\Tapable.js:195:46) undefined
```

```javascript
 try {
            let wxss = compilation.assets[wxssFile].source(); // <-- 这里
              wxss = `@import "/${commonWxssFile}";\n${wxss}`;
              compilation.assets[wxssFile].source = () => wxss;
          } catch (error) {
            console.error(error, wxssFile)
          }
```

虽然错误对build结果没什么影响，但是混在其他错误中间也挺烦人

非专业前端，对webpack了解不深，
是否有什么更优雅方式来使用小程序的自定义组件？  @aOrz

**Comment by aOrz** [comment]
我会把这个地方加个判断，应该就不会报错了

**Comment by aOrz** [comment]
升级 webpack-mpvue-asset-plugin@0.02

**Comment by rchunping** [comment]
@aOrz  完美，赞效率！ 👍

**Comment by fangdiao** [comment]
请问这样做，对长列表性能有明显改善吗
