### ISSUE TITLE
mpvue使用ts-loader报错。

### ISSUE THREAD

**Issue by ToyYan** [Meituan-Dianping/mpvue#42]
vue文件中使用
<script lang="ts" src="./index.ts"></script>
会报如下错误。

` ERROR  Failed to compile with 1 errors                                                                                                                                                                                    12:28:56

 error  in ./src/pages/index/index.ts

Module build failed: TypeError: Cannot read property 'afterCompile' of undefined
    at successfulTypeScriptInstance (/Users/xxx/work/mpvueQuickStart/node_modules/ts-loader/dist/instances.js:147:28)
    at Object.getTypeScriptInstance (/Users/xxx/work/mpvueQuickStart/node_modules/ts-loader/dist/instances.js:48:12)
    at Object.loader (/Users/xxx/work/mpvueQuickStart/node_modules/ts-loader/dist/index.js:16:41)

 @ ./src/pages/index/index.vue 8:0-51
 @ ./src/pages/index/main.js`

**Comment by WingGao** [comment]
@ToyYan 
我用at解决了
https://github.com/WingGao/mpvue-ts-demo/blob/master/build/webpack.base.conf.js

**Comment by anchengjian** [comment]
可以参考 @WingGao 的 [mpvue-ts-demo](https://github.com/WingGao/mpvue-ts-demo)
