### ISSUE TITLE
Module build failed: TypeError: Cannot read property 'createSourceFile' of undefined

### ISSUE THREAD

**Issue by banxi1988** [Meituan-Dianping/mpvue#425]
# [问题简单描述]

```
➜  mpvue-todo (master) ✗ npm run dev

> mpvue-todo@1.0.0 dev /Users/banxi/Workspace/mpvue-todo
> node build/dev-server.js


 ERROR  Failed to compile with 1 errors                                                                                                         4:15:39 PM

Module build failed: TypeError: Cannot read property 'createSourceFile' of undefined
    at parseComponentsDeps (/Users/banxi/Workspace/mpvue-todo/node_modules/mpvue-loader/lib/mp-compiler/parse-ts.js:9:25)
    at Object.compileMPScript (/Users/banxi/Workspace/mpvue-todo/node_modules/mpvue-loader/lib/mp-compiler/index.js:116:16)
    at Object.module.exports (/Users/banxi/Workspace/mpvue-todo/node_modules/mpvue-loader/lib/loader.js:258:30)

```
创建项目后，使用 yarn install 安装依赖。然后编译报错。
yarn.lock 文件中， `mpvue-loader` 版本信息如下：

```
mpvue-loader@^1.0.13:
  version "1.0.13"
  resolved "https://registry.yarnpkg.com/mpvue-loader/-/mpvue-loader-1.0.13.tgz#2b759e5e9be266f49db55a14e2f5b5424805c2eb"
  dependencies:
    babelon "^1.0.5"
    consolidate "^0.14.0"
    hash-sum "^1.0.2"
    js-beautify "^1.6.14"
    loader-utils "^1.1.0"
    lru-cache "^4.1.1"
    postcss "^6.0.6"
    postcss-load-config "^1.1.0"
    postcss-selector-parser "^2.0.0"
    resolve "^1.3.3"
    source-map "^0.5.6"
    vue-hot-reload-api "^2.1.0"
    vue-loader "^13.0.4"
    vue-style-loader "^3.0.0"
    vue-template-es2015-compiler "^1.5.3"
```

**Comment by banxi1988** [comment]
根据上面报错的地方，我找到了对应的代码如下：
`mpvue-loader/lib/mp-compiler/parse-ts.js:9:25`

```js
let ts
try {
  ts = require('typescript')
} catch (e) {

}

function parseComponentsDeps (scriptContent) {
  const sourceFile = ts.createSourceFile('test', scriptContent, ts.ScriptTarget.ESNext, /* setParentNodes */ true)
  return delint(sourceFile)
}
```

所以这里应该是没有在本项目安装 `typescript` 的原因。

建议在上面的 `try catch` 中有异常应该直接输出对应错误，提示 `npm link typescript 或者 npm install -S typescript`
