### ISSUE TITLE
Module build failed: Error: Could not find file

### ISSUE THREAD

**Issue by banxi1988** [Meituan-Dianping/mpvue#426]
# [问题简单描述]
Demo 项目在 ：https://github.com/banxi1988/mpvue-todo

现在编译出现如下的错误，但是实际上 `src/TodoApp.vue` 文件是存在的， 我集成了 ts-loader.

```
 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                 4:50:40 PM

 error  in ./src/TodoApp.vue

Module build failed: Error: Could not find file: '/Users/banxi/Workspace/mpvue-todo/src/TodoApp.vue'.
    at getValidSourceFile (/Users/banxi/Workspace/mpvue-todo/node_modules/typescript/lib/typescript.js:103163:23)
    at Object.getEmitOutput (/Users/banxi/Workspace/mpvue-todo/node_modules/typescript/lib/typescript.js:103506:30)
    at Object.getEmitOutput (/Users/banxi/Workspace/mpvue-todo/node_modules/ts-loader/dist/instances.js:155:41)
    at getEmit (/Users/banxi/Workspace/mpvue-todo/node_modules/ts-loader/dist/index.js:172:35)
    at successLoader (/Users/banxi/Workspace/mpvue-todo/node_modules/ts-loader/dist/index.js:42:11)
    at Object.loader (/Users/banxi/Workspace/mpvue-todo/node_modules/ts-loader/dist/index.js:29:12)

 @ ./src/TodoApp.vue 8:0-116
 @ ./~/babel-loader/lib!./~/mpvue-loader/lib/selector.js?type=script&index=0!./src/App.vue
 @ ./src/App.vue
 @ ./src/main.js
```

**Comment by banxi1988** [comment]
> Module build failed: Error: Could not find file: '/Users/banxi/Workspace/mpvue-todo/src/TodoApp.vue'.

```js
function createLanguageService(host, documentRegistry){
       var program;
        function getValidSourceFile(fileName) {
            var sourceFile = program.getSourceFile(fileName);
            if (!sourceFile) {
                throw new Error("Could not find file: '" + fileName + "'.");
            }
            return sourceFile;
        }
        console.warn("createProgram rootFileNames:", rootFileNames)
        program = ts.createProgram(rootFileNames, newSettings, compilerHost, program);

}
```

然后在 分析对应的 ` function createProgram(rootNames, options, host, oldProgram) {` 函数 。

```js
function createProgram(rootNames, options, host, oldProgram) {
        program = {
            getRootFileNames: function () { return rootNames; },
            getSourceFile: getSourceFile,
       }
 return program;
}
        function getSourceFile(fileName) {
            return getSourceFileByPath(toPath(fileName));
        }
        function getSourceFileByPath(path) {
            return filesByName.get(path);
        }

```

再看看 `filesByName`

```js
        var filesByName = ts.createMap();
```

一路看下来，也没有找出明显的原因。

**Comment by WingGao** [comment]
@banxi1988 配置文件`vue-loader.conf.js`也需要添加如下配置，https://github.com/WingGao/mpvue-ts-demo/blob/dev/build/vue-loader.conf.js

**Comment by banxi1988** [comment]
@WingGao  非常感谢，经测试，  ts-loader 还是会报找不到文件的错误。
awesome-typescript-loader 5.0 会报 watchRun undefined 错误。
换成 4.0.1 测试 OK。 再次表示感谢。
