### ISSUE TITLE
h is not a function;at pages/index/main page handleProxy function

### ISSUE THREAD

**Issue by banxi1988** [Meituan-Dianping/mpvue#440]
# [问题简单描述]

可复现问题仓库： https://github.com/banxi1988/mpvue-todo

**问题复现步骤:**
1. 安装依赖  `yarn`
2. 编译选择 `yarn dev`
3. 在微信开发者工具中打开项目。
4. 在首页中 *请输入待办事项* 的输入框中输入。控制台中即报如下错误。

**期望的表现:**

不报错。

**观察到的表现:**

```
h is not a function;at pages/index/main page handleProxy function
TypeError: h is not a function
    at http://127.0.0.1:63813/appservice/static/js/vendor.js:5446:43
    at Array.forEach (<anonymous>)
    at Vue$3.handleProxyWithVue [as $handleProxyWithVue] (http://127.0.0.1:63813/appservice/static/js/vendor.js:5446:13)
    at e.handleProxy (http://127.0.0.1:63813/appservice/static/js/vendor.js:5096:26)
    at e.<anonymous> (http://127.0.0.1:63813/appservice/__dev__/WAService.js:18:4907)
    at e.a (http://127.0.0.1:63813/appservice/__dev__/WAService.js:17:31002)
    at z (http://127.0.0.1:63813/appservice/__dev__/WAService.js:17:24941)
    at Function.<anonymous> (http://127.0.0.1:63813/appservice/__dev__/WAService.js:17:26562)
    at Object.webviewEventCallback (http://127.0.0.1:63813/appservice/__dev__/WAService.js:18:509)
    at http://127.0.0.1:63813/appservice/__dev__/WAService.js:6:26190
```

![image](https://user-images.githubusercontent.com/726774/39814375-94f15f52-53c6-11e8-9ad9-0b2619d118cd.png)

**Comment by banxi1988** [comment]
@aOrz 我上面给的仓库试了吗？ https://github.com/banxi1988/mpvue-todo

**Comment by banxi1988** [comment]
自己也尝试调试判断一下问题：
1） 其中 handles 的第二项 h 为 undefined
![image](https://user-images.githubusercontent.com/726774/39982151-00e9a81e-5786-11e8-82f0-3745b10d221b.png)

2) 应该是 上面的 getHandles 的返回的问题。
调试进入此函数：
![image](https://user-images.githubusercontent.com/726774/39982490-1f2ab952-5787-11e8-997c-607af80a078d.png)

进一步发现 data.on 数组中第二项为 `undefined`
![image](https://user-images.githubusercontent.com/726774/39982737-dd795b98-5787-11e8-99cb-fbdc39b3b5c0.png)

所以这里需要进一步确认为什么 data.on 数组中的第二个元素为 `undefined`.

从 `Vue` 的模板代码来看：

`      <input id="todo_content" @input="onInputNewTodoContent"  v-model="newTodoContent" name="todo_content" placeholder="请输入待办事项" />` 没有看出来有两个事件处理。

但是构建出来的 VNode 中又确实出现了 undefined.
那可能问题出在构建  VNode 的过程中。

**Comment by banxi1988** [comment]
我手动修正了上面 `res.concat(h)` 没有过滤 undefined 的问题。
然后发现 `@click` 绑定的函数没有生效：
源代码中，UI 有设置 `@click`  
`      <button id="submit-button" type="submit" @click="submit">创建</button>`

对应类中也有 `submit` 方法：

```ts
@Compoment({
  components: {
    TodoItem
  }
})
export default class TodoApp extends Vue {
  todos = [new Todo("学习 JS"), new Todo("学习 CSS"), new Todo("学习 HTML")];
  newTodoContent = "";
  newTodoError = "";

  submit(event: any) {
    let content = this.newTodoContent.trim();
    if (content.length < 1) {
      this.newTodoError = "待办事项内容不能为空";
    } else {
      const todo = new Todo(content);
      this.todos.push(todo);
      this.newTodoContent = '';
    }
    event.preventDefault();
    return false;
  }
}
```


![image](https://user-images.githubusercontent.com/726774/39983582-bdc7ab8a-578a-11e8-9f7e-ba50d7ef98fe.png)

```
```

**Comment by banxi1988** [comment]
@anchengjian  可否看一下这个问题。已经好几天了。 或者说是还需要提供什么其他信息呢？

**Comment by F-loat** [comment]
应该是同时使用了 `@input` 和 `v-model` 的问题

**Comment by banxi1988** [comment]
@F-loat  谢谢回复，帮看一下那后面为什么 button 的 `@click` 绑定没有效果。

**Comment by F-loat** [comment]
@banxi1988 建议你试下不用 class compontent 有没有这些问题，template 部分应该是没问题的，class compontent 相关的我也不是很懂

**Comment by EvanXiang** [comment]
我今天也遇到了这个问题，试了很久一直报这个错，发现因为computed属性和methods方法命名重复了，改了其中一个就不报错了。

**Comment by lhgo-net** [comment]
同问：ui界面绑定事件导致函数名不是函数。
VM1195:1 MiniProgramError
_vm.next is not a function
TypeError: _vm.next is not a function
    at Vue$3.render (http://127.0.0.1:16513/appservice/pages/model/answer/list-temaplet/main.js:168:49)
    at Vue$3.Vue._render (http://127.0.0.1:16513/appservice/common/vendor.js:3692:22)
    at Vue$3.updateComponent (http://127.0.0.1:16513/appservice/common/vendor.js:2212:21)
    at Watcher.get (http://127.0.0.1:16513/appservice/common/vendor.js:2542:25)
    at new Watcher (http://127.0.0.1:16513/appservice/common/vendor.js:2531:12)
    at mountComponent (http://127.0.0.1:16513/appservice/common/vendor.js:2216:17)
    at http://127.0.0.1:16513/appservice/common/vendor.js:5857:14
    at Ze.onReady (http://127.0.0.1:16513/appservice/common/vendor.js:5296:9)
    at Ze.<anonymous> (http://127.0.0.1:16513/appservice/__dev__/WAService.js:2:2202993)
    at Ze.p.__callPageLifeTime__ (http://127.0.0.1:16513/appservice/__dev__/WAService.js:2:2202738)
