### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by kiwenlau** [Meituan-Dianping/mpvue#472]
#### main.js中使用了Fundebug:

```
var fundebug = require('./utils/fundebug.0.2.1.min')
```

#### 报错：

```
thirdScriptError 
 sdk uncaught third Error 
 Cannot assign to read only property 'exports' of object '#<Object>' 
 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.<anonymous> (http://127.0.0.1:61323/appservice/static/js/app.js:287:28)
    at Object.39 (http://127.0.0.1:61323/appservice/static/js/app.js:288:30)
    at __webpack_require__ (http://127.0.0.1:61323/appservice/static/js/manifest.js:55:30)
    at Object.44 (http://127.0.0.1:61323/appservice/static/js/app.js:354:16)
    at __webpack_require__ (http://127.0.0.1:61323/appservice/static/js/manifest.js:55:30)
    at Object.webpackJsonpCallback [as webpackJsonp] (http://127.0.0.1:61323/appservice/static/js/manifest.js:26:23)
    at http://127.0.0.1:61323/appservice/static/js/app.js:1:256
    at require (http://127.0.0.1:61323/appservice/__dev__/WAService.js:18:27248)
    at http://127.0.0.1:61323/appservice/__dev__/WAService.js:18:26997
    at http://127.0.0.1:61323/appservice/app.js:4:1
```
[fundebug.0.2.1.min.js](https://wxjs.fundebug.cn/fundebug.0.2.1.min.js)中使用了module.exports导出fundebug对象。

- 这个错是为什么呢？

根据[Webpack的相关issue](https://github.com/webpack/webpack/issues/4039), 是因为[transform-runtime添加了import语句](https://github.com/webpack/webpack/issues/4039#issuecomment-274094298), 而[import与module.exports不能一起使用](https://github.com/webpack/webpack/issues/4039#issuecomment-273804003)

那么：
- transform-runtime为什么要添加import语句？
- import为什么和module.exports不能一起使用？

还有，如何解决我遇到的问题呢？

**Comment by kiwenlau** [comment]
@linrui1994 这样确实可以解决问题，非常感谢

**Comment by JunaYa** [comment]
项目中用到第三方库 [jsonwebtoken](https://github.com/auth0/node-jsonwebtoken) 不论是以 import 还是 require 方式引入，都会报如下错误提示，按照上述方式修改依然是如此。

错误提示 
```
thirdScriptError sdk uncaught third Error 
util.inherits is not a function 
 TypeError: util.inherits is not a function
    at Object.<anonymous> (http://127.0.0.1:37752/appservice/static/js/vendor.js:22018:6)
    at Object.<anonymous> (http://127.0.0.1:37752/appservice/static/js/vendor.js:22036:30)
    at __webpack_require__ (http://127.0.0.1:37752/appservice/static/js/manifest.js:71:31)
    at Object.<anonymous> (http://127.0.0.1:37752/appservice/static/js/vendor.js:44586:18)
    at __webpack_require__ (http://127.0.0.1:37752/appservice/static/js/manifest.js:71:31)
    at Object.<anonymous> (http://127.0.0.1:37752/appservice/static/js/vendor.js:17845:18)
    at __webpack_require__ (http://127.0.0.1:37752/appservice/static/js/manifest.js:71:31)
    at Object.<anonymous> (http://127.0.0.1:37752/appservice/static/js/vendor.js:21733:11)
    at __webpack_require__ (http://127.0.0.1:37752/appservice/static/js/manifest.js:71:31)
    at Object.global.webpackJsonp.s (http://127.0.0.1:37752/appservice/static/js/vendor.js:44002:11)
```

**Comment by yunhongyao** [comment]
我也遇到这个问题，去掉"plugins": ["transform-vue-jsx","transform-runtime"]中的transform-runtime，我的问题就修复了

**Comment by xyzshen** [comment]
> 将babelrc中的`modules: false`去掉应该就可以了

完美解决，但是问下 这是什么原因造成的
