### ISSUE TITLE
jsEnginScriptError: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by TonyLuo** [Meituan-Dianping/mpvue#715]
# [问题简单描述]
频繁地更新 store里的数组数据，有一定的几率会出现jsEnginScriptError

```
Converting circular structure to JSON
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at Object.a [as publish] (http://127.0.0.1:16723/appservice/appservice?t=1530624034462:1745:8065)
    at i (http://127.0.0.1:16723/appservice/__dev__/WAService.js:6:10882)
    at Object.l [as invokeWebviewMethod] (http://127.0.0.1:16723/appservice/__dev__/WAService.js:13:14674)
    at Function.value (http://127.0.0.1:16723/appservice/__dev__/WAService.js:2:182)
    at e.value (http://127.0.0.1:16723/appservice/__dev__/WAService.js:1:29550)
    at http://127.0.0.1:16723/appservice/static/js/vendor.js:5543:3
    at http://127.0.0.1:16723/appservice/static/js/vendor.js:5531:21
    at VueComponent.updateDataToMP [as $updateDataToMP] (http://127.0.0.1:16723/appservice/static/js/vendor.js:5567:3)
    at VueComponent.patch [as __patch__] (http://127.0.0.1:16723/appservice/static/js/vendor.js:5068:8)
```
**问题复现步骤:**

1. [第一步]
2. [第二步]
3. [其他步骤...]

**期望的表现:**

[在这里描述期望的表现]

**观察到的表现:**
![image](https://user-images.githubusercontent.com/3250305/42222328-74712700-7f07-11e8-8c22-9e3c0a4895cc.png)

[在这里描述观察到的表现]

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by prozwang** [comment]
同样遇到, 不过是在一些低版本的机型会遇到， 楼主是怎么解决的？

**Comment by TonyLuo** [comment]
弃坑了....
