### ISSUE TITLE
config文件名特殊？

### ISSUE THREAD

**Issue by wells1013** [Meituan-Dianping/mpvue#733]
添加一个config 文件就会报错

![image](https://user-images.githubusercontent.com/5172252/42486225-8a8d8846-842d-11e8-9901-c84d1214baa3.png)

```javascript
// config.js
const config = {}
export default config
```

```javascript
//index.js
import config from './config'
import api from './api'
import helper from './helper'
import logger from './logger'
export default {
  config,
  api,
  helper,
  logger
}
```
`config` 这个名字很特殊吗？ 我换成别的名字 build 就没有问题了。错误提示如下:

```
 error  in ./src/utils/index.js

Module build failed: evalmachine.<anonymous>:3
var __babelon_object__ = config;
                         ^

ReferenceError: config is not defined
    at evalmachine.<anonymous>:3:26
    at Script.runInContext (vm.js:102:20)
    at /Users/wells/Documents/work_space/miniapps/mplive/node_modules/babelon/index.js:32:12
    at Object.babelon.eval (/Users/wells/Documents/work_space/miniapps/mplive/node_modules/babelon/index.js:43:31)
    at Property (/Users/wells/Documents/work_space/miniapps/mplive/node_modules/mpvue-loader/lib/mp-compiler/parse.js:34:69)
    at NodePath._call (/Users/wells/Documents/work_space/miniapps/mplive/node_modules/babel-traverse/lib/path/context.js:76:18)
    at NodePath.call (/Users/wells/Documents/work_space/miniapps/mplive/node_modules/babel-traverse/lib/path/context.js:48:17)
    at NodePath.visit (/Users/wells/Documents/work_space/miniapps/mplive/node_modules/babel-traverse/lib/path/context.js:105:12)
    at TraversalContext.visitQueue (/Users/wells/Documents/work_space/miniapps/mplive/node_modules/babel-traverse/lib/context.js:150:16)
    at TraversalContext.visitMultiple (/Users/wells/Documents/work_space/miniapps/mplive/node_modules/babel-traverse/lib/context.js:103:1
7)

 @ ./node_modules/babel-loader/lib!./node_modules/mpvue-loader/lib/selector.js?type=script&index=0!./src/App.vue 4:0-54
 @ ./src/App.vue
 @ ./src/main.js
```

**Comment by JJJYY** [comment]
据说有特殊处理#736
