### ISSUE TITLE
使用外部引入腾讯地图插件出现错误

### ISSUE THREAD

**Issue by canbaozxc** [Meituan-Dianping/mpvue#773]
# [问题简单描述]

**问题复现步骤:**

1. 通过vue指令安装mpvue
2. 在src目录下的utils文件夹中新建map目录并存放好用于微信小程序的qqmap-wx-jssdk.min.js
3. 回到pages目录在index页面引入腾讯地图组件qqmap-wx-jssdk.min.js，代码如下
`var QQMapWX = require('../../utils/map/qqmap-wx-jssdk.js');
var qqmapsdk;
`
4.在页面生命周期created或者mounted里面添加实例化

`// 实例化API核心类
 qqmapsdk = new QQMapWX({
        key: 'DZBBZ-2XSCW-U6IRS-OINHG-32MZZ-6EFF5'
    });
`
   
5.使用qqmapsdk调用组件各种功能
**期望的表现:**

[能够使用实例化的腾讯地图组件，进行城市，地址，周边信息查询]

**观察到的表现:**

出现两个报错
1.thirdScriptError 
 sdk uncaught third Error 
 Cannot assign to read only property 'exports' of object '#<Object>' 
 TypeError: Cannot assign to read only property 'exports' of object '#<Object>'
    at Object.<anonymous> (http://127.0.0.1:36311/appservice/static/js/pages/map/main.js:671:28)
    at Object._ (http://127.0.0.1:36311/appservice/static/js/pages/map/main.js:673:12)
    at __webpack_require__ (http://127.0.0.1:36311/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:36311/appservice/static/js/pages/map/main.js:117:23)
    at __webpack_require__ (http://127.0.0.1:36311/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:36311/appservice/static/js/pages/map/main.js:26:128)
    at __webpack_require__ (http://127.0.0.1:36311/appservice/static/js/manifest.js:71:31)
    at Object._ (http://127.0.0.1:36311/appservice/static/js/pages/map/main.js:13:72)
    at __webpack_require__ (http://127.0.0.1:36311/appservice/static/js/manifest.js:71:31)
    at Object.webpackJsonpCallback [as webpackJsonp] (http://127.0.0.1:36311/appservice/static/js/manifest.js:38:26)
2. pages/map/main.js 出现脚本错误或者未正确调用 Page()

**屏幕截图和动态 GIF 图**

![复现步骤的屏幕截图和动态 GIF 图](图片的 url)

**Comment by FIVELONG** [comment]
请问解决了吗，遇到了相同的问题

**Comment by zxzhgk** [comment]
我也遇到了

**Comment by zxzhgk** [comment]
解决了 把地图SDK放到static下，别让它被webpack 编译就不会报错了

**Comment by zxzhgk** [comment]
https://blog.csdn.net/lq_qing/article/details/85218830

**Comment by ghostsatan** [comment]
VM3607:1 thirdScriptError 
 sdk uncaught third Error 
 Cannot read property 'userAgent' of undefined 
 TypeError: Cannot read property 'userAgent' of undefined
    at http://127.0.0.1:24190/appservice/common/vendor.js:11052:102
    at e.version (http://127.0.0.1:24190/appservice/common/vendor.js:11038:54)
    at http://127.0.0.1:24190/appservice/common/vendor.js:11039:18
    at http://127.0.0.1:24190/appservice/common/vendor.js:11035:20
    at http://127.0.0.1:24190/appservice/common/vendor.js:11036:16
    at a (http://127.0.0.1:24190/appservice/common/vendor.js:11022:25)
    at Object.<anonymous> (http://127.0.0.1:24190/appservice/common/vendor.js:11023:12)
    at Object.t.exports.render.t (http://127.0.0.1:24190/appservice/common/vendor.js:11431:12)
    at e (http://127.0.0.1:24190/appservice/common/vendor.js:6228:23)
    at Object.defineProperty.value (http://127.0.0.1:24190/appservice/common/vendor.js:7706:22)


我是报这个错 不知道问题出在什么地方 有人知道么

**Comment by ghostsatan** [comment]
import QQMapWX from '../../../static/lib/qqmap-wx-jssdk'; 
export default {
  props: ['lat', 'lon'],
  data: {
    controls: [] // 地图控件
  },
  created () {
    // this.mapCtx = wx.createMapContext('mapCon')
    // this.movetoPosition()
    // this.mapCtx.getCenterLocation({
    //    success: (res) => {
    //      console.log(res)
    //    },
    //    fail: ()=>{
    //      console.log(123);
    //    }
    //  })
    this.onLoad();
    this.onShow();
  },
  computed: {
    // 地图控件
    newControl: function () {
      let _data = null
      wx.getSystemInfo({
        success: res => {
          console.log(res);
        }
      })
      return _data
    }
  },
  methods: {
    onLoad (){
      console.log(QQMapWX)
      qqmapsdk = new QQMapWX({
        key: 'PYWBZ-KXNCR-P2SWB-WW6UI-NI7L5-XXXX'
      });
    },
    onShow: function () {
        // 调用接口
        qqmapsdk.search({
            keyword: '酒店',
            success: function (res) {
                console.log(res);
            },
            fail: function (res) {
                console.log(res);
            },
        complete: function (res) {
            console.log(res);
        }
    });
  },
    // 定位到本地坐标
    movetoPosition () {
      this.mapCtx.moveToLocation()
    },
    // 控件点击事件
    bindcontroltap (e) {
      switch (e.mp.controlId) {
        case 1: this.movetoPosition()
          break
        case 2: console.log('2') // this.openCode()
          break
        case 3: wx.navigateTo({
          url: '/pages/personal/main'
        })
      }
    }
  }
}
</script>

我是这样写的  一直报错

 qqmapsdk is not defined

**Comment by Zhengke0110** [comment]
lib/qqmap-wx-jssdk.min.js 的导出方式不支持 Import引入  改用require
