### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by vimcaw** [Meituan-Dianping/mpvue#830]
# [问题简单描述]

**问题复现步骤:**

这是我在移植 SPA 到 mpvue 的时候出现的，其它环境恐怕难以复现。

1. 运行 `npm run dev`

**期望的表现:**

不报错

**观察到的表现:**

出现一个报错，但是编译成功。

控制台输出：

```bash
TypeError: Cannot read property 'indexOf' of undefined
    at Resolver.parse (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\Resolver.js:181:28)
    at Resolver.<anonymous> (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\ParsePlugin.js:15:25)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\tapable\lib\Tapable.js:256:13)
    at runNormal (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\Resolver.js:130:20)
    at Resolver.doResolve (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\Resolver.js:116:3)
    at Resolver.<anonymous> (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\UnsafeCachePlugin.js:37:12)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\tapable\lib\Tapable.js:256:13)
    at runNormal (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\Resolver.js:130:20)
    at Resolver.doResolve (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\Resolver.js:116:3)
    at Resolver.resolve (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\enhanced-resolve\lib\Resolver.js:86:14)
    at resolve (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\webpack\lib\NormalModule.js:133:14)
    at Promise (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\@f-loat\mpvue-loader\lib\mp-compiler\index.js:254:7)
    at new Promise (<anonymous>)
    at Promise.all.Object.keys.map.k (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\@f-loat\mpvue-loader\lib\mp-compiler\index.js:253:12)
    at Array.map (<anonymous>)
    at resolveSrc (C:\Users\vimcaw\Documents\Work\kcshop-mpvue\node_modules\@f-loat\mpvue-loader\lib\mp-compiler\index.js:252:52)
```

进去源码后发现是 `Resolver.prototype.parse` 的参数 `identifier` 为 `undefined` 导致的，进一步到父级，发现 `ParsePlugin.prototype.apply` 函数处理到某项时 `request.request` 为 `undefined`，输出这个 `request` 的值为：
```js
{ 
  context: {},
  path: 'C:\\Users\\vimcaw\\Documents\\Work\\kcshop-mpvue\\src',
  request: undefined
}
```

**屏幕截图和动态 GIF 图**

![image](https://user-images.githubusercontent.com/21964227/43374690-85f77560-93e3-11e8-9b36-f41fb4663b5f.png)

**Comment by anchengjian** [comment]
@F-loat 看看

**Comment by F-loat** [comment]
@vimcaw 最好能提供个 demo 复现

**Comment by tzc123** [comment]
我也出现了这个问题,当我这样引入组件的时候，修改一下引入方式就不报错了。
```javascript
  components: {
    appTitle: require('@/components/app-title.vue').default
  }
```

**Comment by sideFlower** [comment]
我页出现了
