### ISSUE TITLE
components引用大小写导致组件失效

### ISSUE THREAD

**Issue by xiaojue** [Meituan-Dianping/mpvue#9]
```html
<template>
<main>
  <card></card>
</main>
</template>
```
```js
import Card from "@/components/card"

export default{
  components:{
   Card
  }
}
```

如果改成小写就没有问题，这个只有在第一次启动`npm run dev`的时候才会出现，之后无论怎么改都不会好了，因为之前vue的项目是可以这样大写引入的，so。。这算是个bug吧。

Compiling... 报错信息：

```
> subject-wx@1.0.0 dev /Users/xiaojue/Dev/projects/subject-wx
> node build/dev-server.js

TypeError: Cannot read property 'indexOf' of undefined
    at Resolver.parse (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/Resolver.js:181:27)
    at Resolver.<anonymous> (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/ParsePlugin.js:14:25)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:256:13)
    at runNormal (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.<anonymous> (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/UnsafeCachePlugin.js:37:12)
    at Resolver.applyPluginsAsyncSeriesBailResult1 (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_tapable@0.2.8@tapable/lib/Tapable.js:256:13)
    at runNormal (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/Resolver.js:130:20)
    at Resolver.doResolve (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/Resolver.js:116:3)
    at Resolver.resolve (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_enhanced-resolve@3.4.1@enhanced-resolve/lib/Resolver.js:86:14)
    at Object.resolve (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_webpack@2.7.0@webpack/lib/NormalModule.js:130:14)
    at Promise (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_mpvue-loader@1.0.0@mpvue-loader/lib/mp-compiler/index.js:104:14)
    at Promise (<anonymous>)
    at Object.keys.map.k (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_mpvue-loader@1.0.0@mpvue-loader/lib/mp-compiler/index.js:103:14)
    at Array.map (<anonymous>)
    at Object.compileMPScript (/Users/xiaojue/Dev/projects/subject-wx/node_modules/_mpvue-loader@1.0.0@mpvue-loader/lib/mp-compiler/index.js:102:48)
(node:4499) DeprecationWarning: loaderUtils.parseQuery() received a non-string value which can be problematic, see https://github.com/webpack/loader-utils/issues/56
parseQuery() will be replaced with getOptions() in the next major version of loader-utils.
```

**Comment by anchengjian** [comment]
已修复

**Comment by XaignZai** [comment]
https://github.com/XaignZai
